### PR TITLE
Fix silent test failures caused by unimplemented features

### LINKED ISSUE #468: Some generated unit tests ignore failure case
cc @popematt 

A set of unit tests were introduced in PR #451 with [this method signature](https://github.com/amazon-ion/ion-rust/pull/451/files#diff-f4d869788fbfef40174e562fa77827feb9d63b4fc212752344afcf780be9e1f7R470-R472):

```rust
    #[test_resources("ion-tests/iontestdata/good/**/*.ion")]
    #[test_resources("ion-tests/iontestdata/good/**/*.10n")]
    fn test_to_string(file_name: &str) -> IonResult<()> {
      // ...
    }
```

Unfortunately, due to a limitation/bug in the `test_generator` crate that provides the `test_resources` macro, the expanded form of those tests looks like:

```rust
#[allow(non_snake_case)]
fn test_to_string_ion_tests_iontestdata_good_testfile30_ion() {
    test_to_string("ion-tests/iontestdata/good/testfile30.ion".into());
}
```

Notice that `test_to_string` is called but the `Result` it returns is ignored. `rustc` emitted a warning about this, but it was buried in the test output making it easy to miss:

image

Build/test output can be seen [here](https://github.com/amazon-ion/ion-rust/pull/451/checks#step:4:386).

Wrapping the test with an assertion like so:

```rust
    #[test_resources("ion-tests/iontestdata/good/**/*.ion")]
    #[test_resources("ion-tests/iontestdata/good/**/*.10n")]
    fn test_to_string(file_name: &str) {
        match test_to_string_result(file_name) {
            Ok(_) => {}
            Err(e) => panic!("{:?}", e),
        }
    }

    fn test_to_string_result(file_name: &str) -> IonResult<()> {
        // ... original method impl ...
    }
```

causes several errors/failures to be surfaced. I have not investigated the individual errors thoroughly; at least a few will be addressed by @desaikd's work on loading shared symbol tables.

### PR DESCRIPTION
**Pull request by popematt**
**Issue #, if available:**

Fixes #468 

**Description of changes:**

Updates `impl_display_for_element_tests::test_to_string` so that it doesn't return a `Result`. All intermediate results must now be dealt with in this function.

Adds a skip list for failing test cases. All currently skipped tests cases are due to unimplemented functionality.

_By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license._

### CODE REVIEW

File: tests/element_test_vectors.rs [hunk 1]
```diff
@@ -390,26 +390,51 @@ mod impl_display_for_element_tests {
     use super::*;
     use ion_rs::value::native_writer::NativeElementWriter;
     use ion_rs::value::reader::element_reader;
-    use ion_rs::{IonResult, TextWriterBuilder};
+    use ion_rs::TextWriterBuilder;
     use std::fs::read;
 
+    const TO_STRING_SKIP_LIST: [&'static str; 12] = [
```
Comment (zslayton) [inline tests/element_test_vectors.rs:396]: You can get around having to state the length of the array (and updating it with each change) by using a reference:

```suggestion
    const TO_STRING_SKIP_LIST: &[&'static str] = &[
```

**Review by zslayton — APPROVED** [review]
