### PR TITLE
Stop providing misleading row/column locations for binary Ion

### LINKED ISSUE #951: A row/column location should not be available when reading Ion binary
Current implementation does not distinguish between Ion text and Ion binary, and so it will report row/column locations for binary Ion, which could be misleading to users. Additionally, we should ensure that the source location feature has not introduced any performance regression for reading Ion binary, since it seems that the newline counter is counting newlines even for binary input.

### PR DESCRIPTION
**Pull request by popematt**
**Issue #, if available:**

fixes #951 

**Description of changes:**

Adds an `encoding()` method to lazy raw values so that a lazy value can call `self.raw().encoding()` and determine what `IonEncoding` (if any) is backing the current lazy value, and then avoid returning a row/column location for values that are backed by binary Ion.

I also significantly refactored the value location tests, and in doing so, I discovered a few more bugs. The affected test cases are commented out, and I opened #954 and #955.

_By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license._

### CODE REVIEW

File: src/lazy/value.rs [hunk 1]
```diff
@@ -729,27 +782,109 @@ mod tests {
...
+    #[case::no_crlf( "{}\"hello\"",       [(1, 1), (1, 3)])]
+    #[case::lf_lf_lf("{}\n\n\n\"hello\"", [(1, 1), (4, 1)] )]
+    #[case::lf_lf_cr("{}\n\n\r\"hello\"", [(1, 1), (4, 1)] )]
+    #[case::lf_cr_cr("{}\n\r\r\"hello\"", [(1, 1), (4, 1)] )]
+    // FIXME: Currently failing because of https://github.com/amazon-ion/ion-rust/issues/955
+    // #[case::lf_cr_lf("{}\n\r\n\"hello\"", [(1, 1), (3, 1)] )]
+    // #[case::cr_lf_lf("{}\r\n\n\"hello\"", [(1, 1), (3, 1)] )]
+    // #[case::cr_lf_cr("{}\r\n\r\"hello\"", [(1, 1), (3, 1)] )]
+    // #[case::cr_cr_lf("{}\r\r\n\"hello\"", [(1, 1), (3, 1)] )]
+    #[case::cr_cr_cr("{}\r\r\r\"hello\"", [(1, 1), (4, 1)] )]
```
Comment (zslayton) [inline src/lazy/value.rs:795]: Making a note of our offline conversation: I was surprised to see that we support standalone `\r`s in our row/column calculations as these are only (?) used in pre-2000-era mac systems. Counting `\n`s (which inherently includes `\r\n`s) should be a `memchr` SIMD operation while counting `\r`, `\n`, and `\r\n`s separately requires a state machine.

**Review by zslayton — APPROVED** [review]

**Review by desaikd — APPROVED** [review]
